// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Box: typeof import('E:/Projects/Web Projects/online-tools/online-tools-frontend/src/components/Box.vue')['default']
    Btn: typeof import('E:/Projects/online-tools/online-tools-frontend/src/components/Btn.vue')['default']
    Button: typeof import('E:/Projects/online-tools/online-tools-frontend/src/components/Button.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('E:/Projects/Web Projects/online-tools/online-tools-frontend/src/components/Footer.vue')['default']
    README: typeof import('E:/Projects/Web Projects/online-tools/online-tools-frontend/src/components/README.md')['default']
  }
}

export { }
